[build]
  command = "npm i -g npm@9.9.2 && npm --version && npm install --legacy-peer-deps --no-audit --no-fund && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--legacy-peer-deps"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
