[build]
  command = "corepack enable && corepack prepare pnpm@9.15.4 --activate && pnpm --version && pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"
